// ============================================================
// config.do  —  EFM-recovery-RCT-stata (public release)
//
// Path configuration. With no environment variables set, the
// pipeline runs end-to-end on the bundled synthetic dataset:
//
//   data/synthetic/synthetic_crf.xlsx   →   output/run_<TS>/
//
// To run on a differently-named or differently-located CRF, set
// any of these shell variables before `do src/master.do`:
//   export EFM_RAW_DIR    "/path/to/folder/holding/the/xlsx"
//   export EFM_RAW_XLSX   "MyCaseReportForm.xlsx"
//   export EFM_OUTPUT_DIR "/path/to/output"
// ============================================================

version 17

// ---- Promote shell environment variables to Stata globals --
foreach _envvar in EFM_RAW_DIR EFM_RAW_XLSX EFM_OUTPUT_DIR {
    local _val : environment `_envvar'
    if "`_val'" != "" global `_envvar' "`_val'"
}

// ---- Source-code directory (all pipeline .do files live here) ----
// The pipeline is always invoked from the repository root (e.g.
// `do src/master.do`); steps source shared code via "$SRC/...". Data and
// output paths below stay relative to that repo root.
global SRC "src"

// ---- Raw data directory (default: bundled synthetic data) --
global raw_dir = cond("$EFM_RAW_DIR" == "", "data/synthetic", "$EFM_RAW_DIR")

// ---- Source workbook ---------------------------------------
global raw_xlsx = cond("$EFM_RAW_XLSX" == "", "synthetic_crf.xlsx", "$EFM_RAW_XLSX")

// ---- Cleaned (analysis-ready) data directory ---------------
// Regenerated by 00_preprocess from the workbook; gitignored.
global data_dir "data/clean"

// ---- Aggregate / sub-study inputs --------------------------
// reviewer_aggregate.csv (Figure 2/3 reviewer rows) and inter_rater.csv
// (Table S3) live alongside the workbook. See data/synthetic/README.md
// for the synthetic-data provenance.
global aggregate_dir "$raw_dir"

// ---- Output base directory ---------------------------------
global output_base = cond("$EFM_OUTPUT_DIR" == "", "output", "$EFM_OUTPUT_DIR")

// ---- Timestamped run sub-directory -------------------------
local ymd = string(year(today()), "%04.0f") + string(month(today()), "%02.0f") + string(day(today()), "%02.0f")
local hms = subinstr(c(current_time), ":", "", .)
global run_dir "$output_base/run_`ymd'_`hms'"

// ---- Canonical cleaned-data filenames ----------------------
global path_wide          "$data_dir/clean_efm_data.dta"
global path_wide_csv      "$data_dir/clean_efm_data.csv"
global path_long          "$data_dir/checkpoints_long.dta"
global path_long_csv      "$data_dir/checkpoints_long.csv"
global path_doppler       "$data_dir/doppler.dta"
global path_doppler_csv   "$data_dir/doppler.csv"
global path_secondary     "$data_dir/secondary_outcomes.dta"
global path_secondary_csv "$data_dir/secondary_outcomes.csv"

// ---- Create directories ------------------------------------
capture mkdir "$data_dir"
capture mkdir "$output_base"
capture mkdir "$run_dir"

di "Config loaded. Workbook: $raw_dir/$raw_xlsx"
di "Run dir: $run_dir"
